### ISSUE TITLE
Config Service

### ISSUE THREAD

**Issue by mavogel** [SimonFindling/ui-lab#8]
Manage the configurations of all services in a single artifact. See in [piggymetrics](https://github.com/sqshq/PiggyMetrics/#config-service) for details.

**Comment by SimonFindling** [comment]
- pushed the config service to master.
- Config-service is now assigned to hold the application.yml files for all services. therefore he has a "shared" directory in main/resources.
- there is an application.yml which holds the standard configuration, which can be complemented by specific files. These are named <application-name>.yml. Application name and the usage of the config service is declared in bootstrap.yml in every applications resource foulder.
- For test/resources you need to add own application.yml (and/or bootstrap.yml) files which doesn't declare to use the config service. i added those for the existing services.
- The application.yml files in main/resources are not needed anymore, because i added those files to the config-service. They could be deleted, but I kept them for now, so the others can check if something is missing in the new config files.

**Comment by mavogel** [comment]
Nice thank you! 
What's left is fetching the `yml` from the config service for each microservice.

**Comment by mavogel** [comment]
- [ ] clean up each service so that all pull the configs from the `config-service`
