### ISSUE TITLE
Up-to-date API documentation

### ISSUE THREAD

**Issue by Junkern** [SimonFindling/ui-lab#9]
Is this link <http://212.227.198.46:8081/docs/api-guide.html> the newest version of the API documentation?

**Comment by mavogel** [comment]
No we have a newer one. I'll need to finish my feature-branch and merge it to master. I'll give you an update here tomorrow morning.

**Comment by mavogel** [comment]
@Junkern : latest API is here: http://82.165.207.147:8081/docs/api-guide.html

**Comment by florianzier** [comment]
Nice API, great work! I have checked it several times now and think we can consolidate it shortly.

Anyway there are a few points I would like to bring up for discussion. But don't worry, I have only tried to document my statements as much as possible that everyone can follow them anytime. And the last part are only some proposals.


## Account-Service

In multiple examples and payloads:
```
{
 "services": [
   "name":"PRODUCT",
   "name":"CUSTOMER",
   "name":"SALES",
   "name":"VENDORS",
 ]
}
```
Arrays don't have an identifier for each object (like "name" in this example). We should remove them.
```
{
 "services": [
   "PRODUCT",
   "CUSTOMER",
   "SALES",
   "VENDORS",
 ]
}
```

We could also consider to invert some urls:
```
$ curl 'http://DOCKER-HOST:8080/accounts/upgrade/{id}' …
$ curl 'http://DOCKER-HOST:8080/accounts/addservice/{id}' …
$ curl 'http://DOCKER-HOST:8080/accounts/rmservice/{id}' …
```
This way we select the container first, then the instance we want to edit and at least what we want to do with that instance.
```
$ curl 'http://DOCKER-HOST:8080/accounts/{id}/upgrade' …
$ curl 'http://DOCKER-HOST:8080/accounts/{id}/addservice' …
$ curl 'http://DOCKER-HOST:8080/accounts/{id}/rmservice' …
```


### [PUT] Update an existing account for a client
*"Anything but the username can be updated."*
```
$ curl 'http://DOCKER-HOST:8080/accounts' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '{"username":"", "firstname":"", "lastname":"", "company":"", "email":""}'
```
Can we omit the username here? Or shall we use a *PATCH* command instead without the username?


### [PUT] Add new services for a customer
```
$ curl 'http://DOCKER-HOST:8080/accounts/addservice/{id}' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '[ "name":"VENDOR" ]'
```
JSON data should always be sent as object, this array is currently unwrapped.
Also the identifier should be removed within the array, see first statement.

### [PUT] Remove services for a tenant in CUSTOMER state
```
$ curl 'http://DOCKER-HOST:8080/accounts/rmservice/{id}' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '[ "SALES", "VENDOR" ]'
```
Same here. Payload should look like this: `{ "services": [ "SALES", "VENDOR" ] }`


## Customer-Service

### [GET] List all customers of a tenant
```
$ curl 'http://DOCKER-HOST:8080/customers/{tenantId}' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
```

### [GET] List a single customer of a tenant
```
$ curl 'http://DOCKER-HOST:8080/customers/{tenantId}' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
```
I suppose only `/{id}` is missing in the second url for listing a single user. Otherwise ok.


## Vendor-Service

### [PUT] Modify a new product for a tenant
I think this should be *"Modify a new product for a tenant"*, but no big deal.


## Sales-Service
```
$ curl 'http://DOCKER-HOST:8080/sales/{tenantId}' -i -X PUT -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '{"customerId":"","products": [{"name":"", "description":"", "price":"", "quantity":""},{"name":"", "description":"", "price":"", "quantity":""},{"name":"", "description":"", "price":"", "quantity":""}], "total":"", "currency":"EUR"}'
```
Seems like the url is lacking an *{id}* here: `/sales/{tenantId}/{id}`
Otherwise I need an explanation for this part.


## Just some ideas

### Proposal for an alteration of the accounts API for adding/removing services:
**URL:** `$ curl 'http://DOCKER-HOST:8080/accounts/services/{id}' …`
**Payload:** `{ "add": [ "PRODUCT", "CUSTOMER" ], "remove": [ "SALES", "VENDOR" ] }`
**Method:** *PATCH* (instead of *PUT*, because only a small part of the account is changed)

Maybe this could violate current standards, in this case we should consider using a *PATCH* to alter the account info and send the full array with all allowed services.

**URL:** `$ curl 'http://DOCKER-HOST:8080/accounts' …`
**Payload:**`{ "services": [ "name":"PRODUCT", "name":"CUSTOMER", "name":"SALES", ] }`
**Method:** *PATCH*

### [Customer/Product/Vendor/Sales]-Services
If we know which tenant sends the requests respectively our database can only access the specific subset for this tenant, we could also drop the *{tenantId}* from the urls in the public api. But only if this is supported by the gateway, the core services shouldn't have to recheck the authentication details and therefore rely on a proper tenant-id.

### [Customer/Product/Vendor]-Services
If we dont restrict the calls on a single database (containing only data of one tenant) and have consecutive IDs, we could simplify some urls:
```
$ curl 'http://DOCKER-HOST:8080/customers/{tenantId}/{id}' …
$ curl 'http://DOCKER-HOST:8080/products/{tenantId}/{id}' …
$ curl 'http://DOCKER-HOST:8080/vendors/{tenantId}/{id}' …
```
If the customer/product/vendor IDs are unique, we could omit the *{tenantId}*.

**Comment by mavogel** [comment]
@florianzier : I'll add you proposals in the next days. Thanks for the review!

**Comment by Junkern** [comment]
Any of the links posted above are not working :D Where can I take a look at the current backend API?

**Comment by mavogel** [comment]
It was down due to updates. Sorry for that. We try to keep the API-docs now up all the time: http://82.165.207.147:8081/docs/api-guide.html

**Comment by Junkern** [comment]
Ok, next question: What is the IP address to direct the API calls to? `curl 'http://82.165.207.147:8080/accounts' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'` is not working....

**Comment by mavogel** [comment]
`curl -D- -X GET http://82.165.207.147:8081/account/accounts/` works!
- `account` is the forward to the service which can be determined at `http://82.165.207.147:8081/routes`
- and `accounts` is the rest resource defined in the rest controller and which be found at the docs mentioned above. 
- `8080` is the local port which internally forwarded by the docker container.

HTH!

So yes, the docs are not really clear. We will adapt the them and the routes and let you guys know.

**Comment by mavogel** [comment]
## TODO
- [ ] Remove non existing service from API doc
- [ ] Add api doc for product service
- [ ] Finish warehouse api doc
